name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version that will be released"
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # actions/checkout@v2 does a shallow checkout by default
        with:
          fetch-depth: 0

      # - name: update bash
      #   run: |
      #     wget https://ftp.gnu.org/gnu/bash/bash-5.1.8.tar.gz
      #     tar xvf bash-5.1.8.tar.gz
      #     cd bash-5.1.8
      #     ./configure
      #     make
      #     sudo make install

      - name: Create release branch
        run: git checkout -b release-version/${{ github.event.inputs.version }}

      - name: Create Changes
        id: logs
        run: |
          git fetch origin master

          echo "building Changelog"

          changedLog=""
          logs=`git log --format="%an, %s" origin/master..HEAD | grep "Merge pull request"`

          while read -r line;
          do
            echo "line: $line"

            author=`echo $line | grep -oE "^[a-zA-Z0-9\s_\-]+"`
            echo 1
            pull_number=`echo $line | grep -oP "(?<=#)\d+"`
            echo 2
            # branch_name=`echo $line | grep -oE "(from murgatroid99/).+$" | sed -n 's/^from murgatroid99\///p'`
            branch_name=`echo $line | grep -oP "(?<=from ).+" | grep -oP "(?<=\/).+"`
            echo 3
            echo 33
            ticket=$(echo $line | grep -oP "(?<=\/)(PAY-\d+)") || false
            echo 4
            changedLog+=$'\n'"- Author: $author <br>Branch: $branch_name <br>PR: https://github.com/${{ github.repository }}/pull/$pull_number"
            echo 5

            if [[ $(echo $line | grep -oP "(?<=\/)(PAY-\d+)") != "" ]]; then
              ticket=$(echo $line | grep -oP "(?<=\/)(PAY-\d+)")
              changedLog+=" <br>Ticket: [$ticket](https://mcoproduct.atlassian.net/browse/$ticket)"
            fi
            echo 6
          done <<< $logs

          echo "Changelog:"
          echo $changedLog

          echo "::set-output name=changes::$changedLog"

      - name: Update Changelog.md
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.inputs.version }}
          release-notes: ${{ steps.logs.outputs.changes }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "Github Action"
          git config user.email no-reply@gtihub.com

      - name: Bump VERSION file
        run: echo ${{ github.event.inputs.version }} > VERSION

      - name: Bump package.json Version
        run: yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md package.json VERSION
          git commit --message "🚀 bump version to ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new branch
        run: git push origin release-version/${{ github.event.inputs.version }}

      - name: Create pull request
        id: create-pull-request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release-version/${{ github.event.inputs.version }}
          base: master
          title: Release version ${{ github.event.inputs.version }}
          body: |
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.

            The changelog has been updated and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.
            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.

            ## ChangeLog:
            ${{ steps.logs.outputs.changes }}

      # - name: Slack notify (PR)
      #   uses: rtCamp/action-slack-notify@master
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PR }}
      #     SLACK_CHANNEL: playground-for-aaron
      #     SLACK_USERNAME: "FE Deployment"
      #     SLACK_ICON: https://avatars.slack-edge.com/2022-03-16/3250227561252_91f64a484fe3550929bf_48.png
      #     SLACK_TITLE: "The new release has been drafted: `${{ github.event.inputs.version }}`"
      #     SLACK_MESSAGE: "`${{ github.actor }}` drafted new release `${{ github.event.inputs.version }}` for `${{ github.event.repository.name }}`, Please help to review <https://github.com/${{ github.repository }}/pull/${{ steps.create-pull-request.outputs.number }}|Pull Request>  cc @crypto_pay_fe "
      #     SLACK_FOOTER: ""
      #     MSG_MINIMAL: true
      #     SLACK_LINK_NAMES: true

      # - name: Slack notify (ChangeLog)
      #   uses: rtCamp/action-slack-notify@master
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEAM }}
      #     SLACK_CHANNEL: playground-for-aaron #will change to pay-fighter
      #     SLACK_USERNAME: "FE Deployment"
      #     SLACK_ICON: https://avatars.slack-edge.com/2022-03-16/3250227561252_91f64a484fe3550929bf_48.png
      #     SLACK_TITLE: "The new release has been drafted:`"
      #     SLACK_MESSAGE: |
      #       `${{ github.event.repository.name }}`: `${{ github.event.inputs.version }}
      #       ChangeLog:
      #       ```
      #       ${{ steps.logs.outputs.changes }}
      #       ```
      #     SLACK_FOOTER: ""
      #     MSG_MINIMAL: true
      #     SLACK_LINK_NAMES: true
